# Generated by Django 4.1 on 2022-10-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='trailers_film',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
