# Generated by Django 4.1 on 2022-10-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0002_tvshow_trailers_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='trailers_film',
            field=models.URLField(null=True),
        ),
    ]
