# Generated by Django 4.1 on 2022-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserapp',
            name='title_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
